modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="mystics"
version="1.0.0"
displayName="Mystics"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="lucas, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.mystics]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.mystics]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

